---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Pre-tasks before configuration
      ansible.builtin.include_tasks:
        file: "pre-tasks/pull_oci_instance_key.yaml"


- hosts: apigban
  remote_user: "{{ user.remote.name }}"

  tasks:
    - name: Modify kernel parameters
      ansible.builtin.include_tasks: tasks/kernel/net-forwarding.yaml
