---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Pre-tasks before configuration
      ansible.builtin.include_tasks:
        file: "pre-tasks/pull_oci_instance_key.yaml"


- hosts: apigban
  remote_user: "{{ user.remote.name }}"
  become: true

  tasks:
    - name: Modify kernel parameters
      ansible.builtin.include_tasks: tasks/kernel/net-forwarding.yaml
    - name: Update, upgrade, install packages
      ansible.builtin.include_tasks: tasks/packages/packages.yaml
